spring:
    datasource:
        url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    rabbitmq:
        addresses: 127.0.0.1
        port: 5672
        username: guest
        password: guest
        publisher-confirms: true
    redis:
        host: localhost
        port: 6379
        timeout: 600000
        jedis:
          pool:
            max-idle: 8
            max-wait: -1
            min-idle: 0
            max-active: 8
        password:
        database: 0
    data:
      mongodb:
        host: localhost
        port: 27017
        database: test



mybatis:
    mapperLocations: classpath:mybatis/mapper/*.xml
    config-location: classpath:mybatis/mybatis-config.xml
    typeAliasesPackage: com.sire.controller.post.dao


endpoints:
  health:
    sensitive: false
  mappings:
    sensitive: false
  trace:
    sensitive: false
  metrics:
    sensitive: false
  env:
    sensitive: false
  configprops:
    sensitive: false
  beans:
    sensitive: false
  autoconfig:
    sensitive: false